#############################################################################
# Makefile for building: EnneagonGateway
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Apr 28 09:16:15 2018
# Project:  EnneagonGateway.pro
# Template: app
# Command: /opt/qt-4.8.6-arm/bin/qmake -o Makefile EnneagonGateway.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-fsl-linux-gnueabi-gcc
CXX           = arm-fsl-linux-gnueabi-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-4.8.6-arm/mkspecs/qws/linux-arm-g++ -I. -I/opt/qt-4.8.6-arm/include/QtCore -I/opt/qt-4.8.6-arm/include/QtNetwork -I/opt/qt-4.8.6-arm/include/QtSql -I/opt/qt-4.8.6-arm/include -I.
LINK          = arm-fsl-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-4.8.6-arm/lib
LIBS          = $(SUBLIBS)  -L/opt/qt-4.8.6-arm/lib -lcryptopp -lqamqp -lQtSql -L/opt/openssl/lib -L/opt/qt-4.8.6-arm/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-fsl-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-4.8.6-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-fsl-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		device/canworkerthread.cpp \
		device/canwrapper.cpp \
		utility/cdatahelper.cpp \
		utility/json.cpp \
		network/creghttp.cpp \
		manage/cmanage.cpp \
		network/ccardverifyhttphandler.cpp \
		network/cflownohttp.cpp \
		pile/cenneagonconnector.cpp \
		manage/capp.cpp \
		pile/cconnectormanager.cpp \
		pile/cverify.cpp \
		pile/cconnectorstatus.cpp \
		pile/cbasewarning.cpp \
		pile/cconnectororder.cpp \
		pile/cmodule.cpp \
		network/cstatehttp.cpp \
		pile/crecordorder.cpp \
		device/ccandatapacker.cpp \
		network/crabbitmq.cpp \
		network/cconsumehttp.cpp \
		network/crecordhttp.cpp \
		utility/cdatauploader.cpp \
		network/cremotesocket.cpp \
		network/cbookorderhttp.cpp \
		network/cbookorderupdatehttp.cpp \
		network/cwechatrefund.cpp \
		network/calirefund.cpp moc_canworkerthread.cpp \
		moc_cdatahelper.cpp \
		moc_creghttp.cpp \
		moc_cmanage.cpp \
		moc_ccardverifyhttphandler.cpp \
		moc_cflownohttp.cpp \
		moc_cenneagonconnector.cpp \
		moc_capp.cpp \
		moc_cconnectormanager.cpp \
		moc_cstatehttp.cpp \
		moc_crabbitmq.cpp \
		moc_cconsumehttp.cpp \
		moc_crecordhttp.cpp \
		moc_cdatauploader.cpp \
		moc_cremotesocket.cpp \
		moc_cbookorderhttp.cpp \
		moc_cbookorderupdatehttp.cpp \
		moc_cwechatrefund.cpp \
		moc_calirefund.cpp
OBJECTS       = main.o \
		canworkerthread.o \
		canwrapper.o \
		cdatahelper.o \
		json.o \
		creghttp.o \
		cmanage.o \
		ccardverifyhttphandler.o \
		cflownohttp.o \
		cenneagonconnector.o \
		capp.o \
		cconnectormanager.o \
		cverify.o \
		cconnectorstatus.o \
		cbasewarning.o \
		cconnectororder.o \
		cmodule.o \
		cstatehttp.o \
		crecordorder.o \
		ccandatapacker.o \
		crabbitmq.o \
		cconsumehttp.o \
		crecordhttp.o \
		cdatauploader.o \
		cremotesocket.o \
		cbookorderhttp.o \
		cbookorderupdatehttp.o \
		cwechatrefund.o \
		calirefund.o \
		moc_canworkerthread.o \
		moc_cdatahelper.o \
		moc_creghttp.o \
		moc_cmanage.o \
		moc_ccardverifyhttphandler.o \
		moc_cflownohttp.o \
		moc_cenneagonconnector.o \
		moc_capp.o \
		moc_cconnectormanager.o \
		moc_cstatehttp.o \
		moc_crabbitmq.o \
		moc_cconsumehttp.o \
		moc_crecordhttp.o \
		moc_cdatauploader.o \
		moc_cremotesocket.o \
		moc_cbookorderhttp.o \
		moc_cbookorderupdatehttp.o \
		moc_cwechatrefund.o \
		moc_calirefund.o
DIST          = /opt/qt-4.8.6-arm/mkspecs/common/unix.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/linux.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/gcc-base.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/g++-base.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/g++-unix.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/qws.conf \
		/opt/qt-4.8.6-arm/mkspecs/qconfig.pri \
		/opt/qt-4.8.6-arm/mkspecs/features/qt_functions.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/qt_config.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/default_pre.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/release.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/default_post.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/shared.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/warn_on.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/qt.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/unix/thread.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/moc.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/resources.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/uic.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/yacc.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/lex.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/include_source_dir.prf \
		EnneagonGateway.pro
QMAKE_TARGET  = EnneagonGateway
DESTDIR       = 
TARGET        = EnneagonGateway

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EnneagonGateway.pro  /opt/qt-4.8.6-arm/mkspecs/qws/linux-arm-g++/qmake.conf /opt/qt-4.8.6-arm/mkspecs/common/unix.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/linux.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/gcc-base.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/g++-base.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/g++-unix.conf \
		/opt/qt-4.8.6-arm/mkspecs/common/qws.conf \
		/opt/qt-4.8.6-arm/mkspecs/qconfig.pri \
		/opt/qt-4.8.6-arm/mkspecs/features/qt_functions.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/qt_config.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/default_pre.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/release.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/default_post.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/shared.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/warn_on.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/qt.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/unix/thread.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/moc.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/resources.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/uic.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/yacc.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/lex.prf \
		/opt/qt-4.8.6-arm/mkspecs/features/include_source_dir.prf \
		/opt/qt-4.8.6-arm/lib/libQtSql.prl \
		/opt/qt-4.8.6-arm/lib/libQtCore.prl \
		/opt/qt-4.8.6-arm/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile EnneagonGateway.pro
/opt/qt-4.8.6-arm/mkspecs/common/unix.conf:
/opt/qt-4.8.6-arm/mkspecs/common/linux.conf:
/opt/qt-4.8.6-arm/mkspecs/common/gcc-base.conf:
/opt/qt-4.8.6-arm/mkspecs/common/gcc-base-unix.conf:
/opt/qt-4.8.6-arm/mkspecs/common/g++-base.conf:
/opt/qt-4.8.6-arm/mkspecs/common/g++-unix.conf:
/opt/qt-4.8.6-arm/mkspecs/common/qws.conf:
/opt/qt-4.8.6-arm/mkspecs/qconfig.pri:
/opt/qt-4.8.6-arm/mkspecs/features/qt_functions.prf:
/opt/qt-4.8.6-arm/mkspecs/features/qt_config.prf:
/opt/qt-4.8.6-arm/mkspecs/features/exclusive_builds.prf:
/opt/qt-4.8.6-arm/mkspecs/features/default_pre.prf:
/opt/qt-4.8.6-arm/mkspecs/features/release.prf:
/opt/qt-4.8.6-arm/mkspecs/features/default_post.prf:
/opt/qt-4.8.6-arm/mkspecs/features/shared.prf:
/opt/qt-4.8.6-arm/mkspecs/features/warn_on.prf:
/opt/qt-4.8.6-arm/mkspecs/features/qt.prf:
/opt/qt-4.8.6-arm/mkspecs/features/unix/thread.prf:
/opt/qt-4.8.6-arm/mkspecs/features/moc.prf:
/opt/qt-4.8.6-arm/mkspecs/features/resources.prf:
/opt/qt-4.8.6-arm/mkspecs/features/uic.prf:
/opt/qt-4.8.6-arm/mkspecs/features/yacc.prf:
/opt/qt-4.8.6-arm/mkspecs/features/lex.prf:
/opt/qt-4.8.6-arm/mkspecs/features/include_source_dir.prf:
/opt/qt-4.8.6-arm/lib/libQtSql.prl:
/opt/qt-4.8.6-arm/lib/libQtCore.prl:
/opt/qt-4.8.6-arm/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile EnneagonGateway.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EnneagonGateway1.0.0 || $(MKDIR) .tmp/EnneagonGateway1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EnneagonGateway1.0.0/ && $(COPY_FILE) --parents device/canworkerthread.h device/canwrapper.h utility/cdatahelper.h utility/json.h network/creghttp.h pile/cgundefine.h manage/cmanage.h network/ccardverifyhttphandler.h device/ccandatapacker.h network/cflownohttp.h pile/cenneagonconnector.h manage/capp.h pile/cconnectormanager.h pile/cverify.h pile/cconnectorstatus.h pile/cbasewarning.h pile/cconnectororder.h pile/cmodule.h network/cstatehttp.h pile/crecordorder.h utility/aeshandler.h network/crabbitmq.h network/cconsumehttp.h network/crecordhttp.h utility/cdatauploader.h network/cremotesocket.h network/cbookorderhttp.h network/cbookorderupdatehttp.h network/cwechatrefund.h network/calirefund.h .tmp/EnneagonGateway1.0.0/ && $(COPY_FILE) --parents main.cpp device/canworkerthread.cpp device/canwrapper.cpp utility/cdatahelper.cpp utility/json.cpp network/creghttp.cpp manage/cmanage.cpp network/ccardverifyhttphandler.cpp network/cflownohttp.cpp pile/cenneagonconnector.cpp manage/capp.cpp pile/cconnectormanager.cpp pile/cverify.cpp pile/cconnectorstatus.cpp pile/cbasewarning.cpp pile/cconnectororder.cpp pile/cmodule.cpp network/cstatehttp.cpp pile/crecordorder.cpp device/ccandatapacker.cpp network/crabbitmq.cpp network/cconsumehttp.cpp network/crecordhttp.cpp utility/cdatauploader.cpp network/cremotesocket.cpp network/cbookorderhttp.cpp network/cbookorderupdatehttp.cpp network/cwechatrefund.cpp network/calirefund.cpp .tmp/EnneagonGateway1.0.0/ && (cd `dirname .tmp/EnneagonGateway1.0.0` && $(TAR) EnneagonGateway1.0.0.tar EnneagonGateway1.0.0 && $(COMPRESS) EnneagonGateway1.0.0.tar) && $(MOVE) `dirname .tmp/EnneagonGateway1.0.0`/EnneagonGateway1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EnneagonGateway1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_canworkerthread.cpp moc_cdatahelper.cpp moc_creghttp.cpp moc_cmanage.cpp moc_ccardverifyhttphandler.cpp moc_cflownohttp.cpp moc_cenneagonconnector.cpp moc_capp.cpp moc_cconnectormanager.cpp moc_cstatehttp.cpp moc_crabbitmq.cpp moc_cconsumehttp.cpp moc_crecordhttp.cpp moc_cdatauploader.cpp moc_cremotesocket.cpp moc_cbookorderhttp.cpp moc_cbookorderupdatehttp.cpp moc_cwechatrefund.cpp moc_calirefund.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_canworkerthread.cpp moc_cdatahelper.cpp moc_creghttp.cpp moc_cmanage.cpp moc_ccardverifyhttphandler.cpp moc_cflownohttp.cpp moc_cenneagonconnector.cpp moc_capp.cpp moc_cconnectormanager.cpp moc_cstatehttp.cpp moc_crabbitmq.cpp moc_cconsumehttp.cpp moc_crecordhttp.cpp moc_cdatauploader.cpp moc_cremotesocket.cpp moc_cbookorderhttp.cpp moc_cbookorderupdatehttp.cpp moc_cwechatrefund.cpp moc_calirefund.cpp
moc_canworkerthread.cpp: device/canwrapper.h \
		device/canworkerthread.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) device/canworkerthread.h -o moc_canworkerthread.cpp

moc_cdatahelper.cpp: utility/cdatahelper.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) utility/cdatahelper.h -o moc_cdatahelper.cpp

moc_creghttp.cpp: utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		network/creghttp.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/creghttp.h -o moc_creghttp.cpp

moc_cmanage.cpp: device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h \
		manage/cmanage.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) manage/cmanage.h -o moc_cmanage.cpp

moc_ccardverifyhttphandler.cpp: utility/json.h \
		device/ccandatapacker.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		network/ccardverifyhttphandler.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/ccardverifyhttphandler.h -o moc_ccardverifyhttphandler.cpp

moc_cflownohttp.cpp: utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		network/cflownohttp.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/cflownohttp.h -o moc_cflownohttp.cpp

moc_cenneagonconnector.cpp: pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h \
		pile/cenneagonconnector.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) pile/cenneagonconnector.h -o moc_cenneagonconnector.cpp

moc_capp.cpp: utility/cdatahelper.h \
		manage/capp.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) manage/capp.h -o moc_capp.cpp

moc_cconnectormanager.cpp: pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h \
		pile/cconnectormanager.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) pile/cconnectormanager.h -o moc_cconnectormanager.cpp

moc_cstatehttp.cpp: utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		network/cstatehttp.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/cstatehttp.h -o moc_cstatehttp.cpp

moc_crabbitmq.cpp: qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		manage/capp.h \
		utility/cdatahelper.h \
		utility/aeshandler.h \
		utility/json.h \
		pile/cconnectormanager.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		network/crabbitmq.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/crabbitmq.h -o moc_crabbitmq.cpp

moc_cconsumehttp.cpp: utility/json.h \
		network/cconsumehttp.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/cconsumehttp.h -o moc_cconsumehttp.cpp

moc_crecordhttp.cpp: utility/json.h \
		network/crecordhttp.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/crecordhttp.h -o moc_crecordhttp.cpp

moc_cdatauploader.cpp: utility/cdatahelper.h \
		utility/cdatauploader.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) utility/cdatauploader.h -o moc_cdatauploader.cpp

moc_cremotesocket.cpp: manage/capp.h \
		utility/cdatahelper.h \
		utility/json.h \
		network/cremotesocket.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/cremotesocket.h -o moc_cremotesocket.cpp

moc_cbookorderhttp.cpp: utility/json.h \
		device/ccandatapacker.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		network/cbookorderhttp.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/cbookorderhttp.h -o moc_cbookorderhttp.cpp

moc_cbookorderupdatehttp.cpp: utility/json.h \
		device/ccandatapacker.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		network/cbookorderupdatehttp.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/cbookorderupdatehttp.h -o moc_cbookorderupdatehttp.cpp

moc_cwechatrefund.cpp: utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		network/cwechatrefund.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/cwechatrefund.h -o moc_cwechatrefund.cpp

moc_calirefund.cpp: utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		network/calirefund.h
	/opt/qt-4.8.6-arm/bin/moc $(DEFINES) $(INCPATH) network/calirefund.h -o moc_calirefund.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

canworkerthread.o: device/canworkerthread.cpp device/canworkerthread.h \
		device/canwrapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canworkerthread.o device/canworkerthread.cpp

canwrapper.o: device/canwrapper.cpp device/canwrapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canwrapper.o device/canwrapper.cpp

cdatahelper.o: utility/cdatahelper.cpp utility/cdatahelper.h \
		manage/capp.h \
		pile/cconnectormanager.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		utility/cdatauploader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdatahelper.o utility/cdatahelper.cpp

json.o: utility/json.cpp utility/json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json.o utility/json.cpp

creghttp.o: network/creghttp.cpp network/creghttp.h \
		utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creghttp.o network/creghttp.cpp

cmanage.o: manage/cmanage.cpp manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmanage.o manage/cmanage.cpp

ccardverifyhttphandler.o: network/ccardverifyhttphandler.cpp network/ccardverifyhttphandler.h \
		utility/json.h \
		device/ccandatapacker.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ccardverifyhttphandler.o network/ccardverifyhttphandler.cpp

cflownohttp.o: network/cflownohttp.cpp network/cflownohttp.h \
		utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		pile/cconnectormanager.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cflownohttp.o network/cflownohttp.cpp

cenneagonconnector.o: pile/cenneagonconnector.cpp pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cenneagonconnector.o pile/cenneagonconnector.cpp

capp.o: manage/capp.cpp manage/capp.h \
		utility/cdatahelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o capp.o manage/capp.cpp

cconnectormanager.o: pile/cconnectormanager.cpp pile/cconnectormanager.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cconnectormanager.o pile/cconnectormanager.cpp

cverify.o: pile/cverify.cpp pile/cverify.h \
		device/ccandatapacker.h \
		pile/cgundefine.h \
		utility/json.h \
		manage/capp.h \
		utility/cdatahelper.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cverify.o pile/cverify.cpp

cconnectorstatus.o: pile/cconnectorstatus.cpp pile/cconnectorstatus.h \
		utility/json.h \
		pile/cgundefine.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cconnectorstatus.o pile/cconnectorstatus.cpp

cbasewarning.o: pile/cbasewarning.cpp pile/cbasewarning.h \
		utility/cdatahelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cbasewarning.o pile/cbasewarning.cpp

cconnectororder.o: pile/cconnectororder.cpp pile/cconnectororder.h \
		manage/capp.h \
		utility/cdatahelper.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cconnectororder.o pile/cconnectororder.cpp

cmodule.o: pile/cmodule.cpp pile/cmodule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmodule.o pile/cmodule.cpp

cstatehttp.o: network/cstatehttp.cpp network/cstatehttp.h \
		utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cstatehttp.o network/cstatehttp.cpp

crecordorder.o: pile/crecordorder.cpp pile/crecordorder.h \
		manage/capp.h \
		utility/cdatahelper.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		utility/aeshandler.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crecordorder.o pile/crecordorder.cpp

ccandatapacker.o: device/ccandatapacker.cpp device/ccandatapacker.h \
		pile/cconnectormanager.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		utility/cdatahelper.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		manage/capp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ccandatapacker.o device/ccandatapacker.cpp

crabbitmq.o: network/crabbitmq.cpp network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		manage/capp.h \
		utility/cdatahelper.h \
		utility/aeshandler.h \
		utility/json.h \
		pile/cconnectormanager.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		utility/cdatauploader.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crabbitmq.o network/crabbitmq.cpp

cconsumehttp.o: network/cconsumehttp.cpp network/cconsumehttp.h \
		utility/json.h \
		manage/capp.h \
		utility/cdatahelper.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cconsumehttp.o network/cconsumehttp.cpp

crecordhttp.o: network/crecordhttp.cpp network/crecordhttp.h \
		utility/json.h \
		manage/capp.h \
		utility/cdatahelper.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crecordhttp.o network/crecordhttp.cpp

cdatauploader.o: utility/cdatauploader.cpp utility/cdatauploader.h \
		utility/cdatahelper.h \
		manage/capp.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		utility/json.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		pile/cconnectormanager.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cdatauploader.o utility/cdatauploader.cpp

cremotesocket.o: network/cremotesocket.cpp network/cremotesocket.h \
		manage/capp.h \
		utility/cdatahelper.h \
		utility/json.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		utility/aeshandler.h \
		pile/cconnectormanager.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cremotesocket.o network/cremotesocket.cpp

cbookorderhttp.o: network/cbookorderhttp.cpp network/cbookorderhttp.h \
		utility/json.h \
		device/ccandatapacker.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cbookorderhttp.o network/cbookorderhttp.cpp

cbookorderupdatehttp.o: network/cbookorderupdatehttp.cpp network/cbookorderupdatehttp.h \
		utility/json.h \
		device/ccandatapacker.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cbookorderupdatehttp.o network/cbookorderupdatehttp.cpp

cwechatrefund.o: network/cwechatrefund.cpp network/cwechatrefund.h \
		utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		pile/cconnectormanager.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/calirefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cwechatrefund.o network/cwechatrefund.cpp

calirefund.o: network/calirefund.cpp network/calirefund.h \
		utility/json.h \
		utility/aeshandler.h \
		manage/capp.h \
		utility/cdatahelper.h \
		pile/cconnectormanager.h \
		pile/cenneagonconnector.h \
		pile/cgundefine.h \
		pile/cverify.h \
		device/ccandatapacker.h \
		pile/cconnectorstatus.h \
		pile/cbasewarning.h \
		pile/cconnectororder.h \
		pile/crecordorder.h \
		manage/cmanage.h \
		device/canworkerthread.h \
		device/canwrapper.h \
		utility/cdatauploader.h \
		network/crabbitmq.h \
		qamqp/qamqpclient.h \
		qamqp/qamqpglobal.h \
		qamqp/qamqpexchange.h \
		qamqp/qamqptable.h \
		qamqp/qamqpchannel.h \
		qamqp/qamqpmessage.h \
		qamqp/qamqpqueue.h \
		network/cremotesocket.h \
		network/creghttp.h \
		network/ccardverifyhttphandler.h \
		network/cstatehttp.h \
		network/cflownohttp.h \
		network/cconsumehttp.h \
		network/crecordhttp.h \
		network/cbookorderhttp.h \
		network/cbookorderupdatehttp.h \
		network/cwechatrefund.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calirefund.o network/calirefund.cpp

moc_canworkerthread.o: moc_canworkerthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canworkerthread.o moc_canworkerthread.cpp

moc_cdatahelper.o: moc_cdatahelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cdatahelper.o moc_cdatahelper.cpp

moc_creghttp.o: moc_creghttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_creghttp.o moc_creghttp.cpp

moc_cmanage.o: moc_cmanage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmanage.o moc_cmanage.cpp

moc_ccardverifyhttphandler.o: moc_ccardverifyhttphandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ccardverifyhttphandler.o moc_ccardverifyhttphandler.cpp

moc_cflownohttp.o: moc_cflownohttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cflownohttp.o moc_cflownohttp.cpp

moc_cenneagonconnector.o: moc_cenneagonconnector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cenneagonconnector.o moc_cenneagonconnector.cpp

moc_capp.o: moc_capp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_capp.o moc_capp.cpp

moc_cconnectormanager.o: moc_cconnectormanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cconnectormanager.o moc_cconnectormanager.cpp

moc_cstatehttp.o: moc_cstatehttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cstatehttp.o moc_cstatehttp.cpp

moc_crabbitmq.o: moc_crabbitmq.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_crabbitmq.o moc_crabbitmq.cpp

moc_cconsumehttp.o: moc_cconsumehttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cconsumehttp.o moc_cconsumehttp.cpp

moc_crecordhttp.o: moc_crecordhttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_crecordhttp.o moc_crecordhttp.cpp

moc_cdatauploader.o: moc_cdatauploader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cdatauploader.o moc_cdatauploader.cpp

moc_cremotesocket.o: moc_cremotesocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cremotesocket.o moc_cremotesocket.cpp

moc_cbookorderhttp.o: moc_cbookorderhttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cbookorderhttp.o moc_cbookorderhttp.cpp

moc_cbookorderupdatehttp.o: moc_cbookorderupdatehttp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cbookorderupdatehttp.o moc_cbookorderupdatehttp.cpp

moc_cwechatrefund.o: moc_cwechatrefund.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cwechatrefund.o moc_cwechatrefund.cpp

moc_calirefund.o: moc_calirefund.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calirefund.o moc_calirefund.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

